<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{{ $type }}</title>
  <style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; margin: 20px; }
    h1 { color: #c46c6c; font-size: 18px; text-align: center; margin-bottom: 10px; }
    h4 { text-align: center; margin-bottom: 20px; color: #555; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th, td { border: 1px solid #eee; padding: 8px; text-align: left; }
    th { background: #f9eaea; color: #b55b5b; }
    tr:nth-child(even) { background: #fdf7f7; }
    .footer { text-align: center; font-size: 10px; color: #999; margin-top: 30px; }
  </style>
</head>
<body>
  <h1>{{ $type }}</h1>
  <h4>From {{ $from }} to {{ $to }}</h4>

  <table>
    <thead>
      <tr>
        @if(isset($data[0]) && is_array($data[0]))
          @foreach(array_keys($data[0]) as $col)
            <th>{{ ucwords(str_replace('_', ' ', $col)) }}</th>
          @endforeach
        @else
          <th>No data</th>
        @endif
      </tr>
    </thead>
    <tbody>
      @forelse($data as $row)
        <tr>
          @foreach($row as $value)
            <td>{{ $value }}</td>
          @endforeach
        </tr>
      @empty
        <tr><td colspan="10" style="text-align:center;">No records found</td></tr>
      @endforelse
    </tbody>
  </table>

  <div class="footer">
    Generated by appt.live | {{ now()->format('d M Y h:i A') }}
  </div>
</body>
</html>
